### ISSUE TITLE
Managing ambiguous bases

### ISSUE THREAD

**Issue by MolEcologist** [lykaust15/DeepSimulator#1]
I've been attempting to simulate reads from a rat genome, however in cases where there are ambiguous bases ("N"s), the simulator spits out an error and fails to complete. At the moment i'm having to manually remove the N's from the genomes before simulating, though this isn't very efficient.
I know another simulator just replaces the Ns with a random base, though perhaps it might be better to re-sample until the sampled_read.fasta contains no ambiguous bases.

**Comment by MolEcologist** [comment]
Could you just check that the script is utilising the pre-processed version? As currently the main.sh script just gets stuck at the preprocessing step and doesn't continue

**Comment by MolEcologist** [comment]
I'm not sure if this is how you're processing it, but may I suggest it randomly replace the N's in the sampled_read.fasta rather than genome? As when i simulate reads using a full genome, it will take an incredibly long time

**Comment by lykaust15** [comment]
@MolEcologist 
Thank you for reporting the speed issue. I think your genome is large with lots of Ns.In the previous version, I did not test on the large genome. 
This time I accelerate the speed by 5 times for the random replacement. By still, deletion is much faster than random replace by a factor of 50.
By the way, may I have your genome? I would like to use it to benchmark the Ns random replacement. Currently, I only tested on a 48K genome.

**Comment by MolEcologist** [comment]
https://www.ncbi.nlm.nih.gov/genome?term=rattus%20norvegicus is the genome, though i've been testing on only this chromosome specifically https://www.ncbi.nlm.nih.gov/nuccore/NC_005111.4

My concern with simply deleting them, is that when BLASTing the reads back against a database, or aligning the reads to a reference, two regions separated by Ns that wouldnt otherwise be found together, would be simulated as though they were next to each other i.e

ATATCNNNGTGT would be simulated as ATATCGTGT

Whereas if the reads were either resampled till no N's were found in the sampled_read.fasta, or Ns were replaced randomly in the sampled_read.fasta file (rather than replacing all Ns in the genome), these issues could be avoided - and it would be significantly faster.

**Comment by lykaust15** [comment]
@MolEcologist 

Thank you very much!
I just test on the large genome which is 52Mb.
The random replacement would take 9s. Is this speed fine?
Considering the final read, random replacement before sampling or after sampling would give similar results. On the other hand, if the genome is small and the coverage is large, random replacement after sampling would have too much overhead and the ground truth is not fixed. We have to tradeoff those issues.
```
In [3]: len(genome)
Out[3]: 52716770

In [4]: ^Igenome = genome.upper()

In [5]: %time temp = genome.replace('N','')
CPU times: user 91.4 ms, sys: 14.3 ms, total: 106 ms
Wall time: 106 ms

In [6]: %time temp = replace_n(genome)
CPU times: user 7.85 s, sys: 1.29 s, total: 9.14 s
Wall time: 9.12 s
```

**Comment by MolEcologist** [comment]
Brilliant, it works great! You make a good point about random replacement on smaller genomes! Thanks for the quick updates
