### ISSUE TITLE
Unable to run the install script 

### ISSUE THREAD

**Issue by samyuktr** [lykaust15/DeepSimulator#10]
When I try and run the install script according to the README, I'm facing this - 
```
./install.sh: line 15: deactivate: No such file or directory
./install.sh: line 18: conda: command not found
./install.sh: line 19: conda: command not found
./install.sh: line 20: activate: No such file or directory
./install.sh: line 24: deactivate: No such file or directory
```

I have already installed anaconda and my version is - `conda 4.5.12`
Could you please tell me how to get past this? 

Thank you in advance.

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest! 
It seems conda is not installed correctly. Maybe the path is not set correctly.
We can see that:
```
./install.sh: line 18: conda: command not found
```
That means conda can't be found in the path variable.
