### ISSUE TITLE
Default length distribution

### ISSUE THREAD

**Issue by evgisa** [lykaust15/DeepSimulator#11]
Hi, in the Supplementary material of DeepSimulator as well as in the paper 'DeepSimulator: a deep simulator for Nanopore sequencing' it is stated that the default length distribution is the mixed gamma but when looking at deep_simulator.sh I found out that default is 2, which corresponds to alpha distribution. Is this the case or I'm wrong?

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest in our tool!
That's a very good question. You are not wrong, but we have different understandings of 'default parameters'. When I used this simulator, I will change the 'deep_simulator.sh' file freely, so the parameter setting in that file are free parameters, in my opinion. If you check the 'sampling.py' file, you will find that the default parameter is the mixed gamma for that distribution:
```
	parser.add_argument('-d', action='store', dest='dis', default=3,
		type=int, help='choose from the following distribution: \
		1: beta_distribution, 2: alpha_distribution, 3: mixed_gamma_dis \
		default: 3. If the read length drawn from the distribution is \
		larger than the length of the genome, the value is clipped to the\
		length of the genome')
```
So feel free to change anything in 'deep_simulator.sh', it is a collection of commands which we usually enter in the shell. We build that file, in fact, for the users' convenience. Techniquely, the tool can still work without that file, but in that case, the user will be a little bit busier when using the tool.

**Comment by lykaust15** [comment]
For your reference, we have also changed the parameters in the 'deep_simulator.sh' file. Now the default parameters in that file are consistent with the paper.
Feel free to let us know if you have further questions. Have a good day!

**Comment by evgisa** [comment]
Thank you so much for your quick response! Have a nice day!
