### ISSUE TITLE
[feature suggestion] adding an option to control random seed?

### ISSUE THREAD

**Issue by yjx1217** [lykaust15/DeepSimulator#14]
Hello,

I don't know how deepsimulator perform its random sampling but it will be good if an option can be provided to control the random seed used for the simulation to ensure the repeatability of the simulation study. Thanks for consideration!

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing, thank you very much for such a nice suggestion!

**Comment by lykaust15** [comment]
Hi, for your reference, this feature has been implemented. 
Feel free to check and criticize.
