### ISSUE TITLE
DeepSimulator may overide specified thread numbers (-c )

### ISSUE THREAD

**Issue by yjx1217** [lykaust15/DeepSimulator#15]
Hello,

First of all, many thanks for the quick response and feature enhancement for my previous comments. For now, I noticed that DeepSimulator may override user-specified thread number (by -c). For example, in my current run, I set "-c 4" to launch the run but in reality DeepSimulator is using >20 threads at the moment for "fast5_modify_signal.py". So it will be great if you can take a look into this issue. Thanks in advance!

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing, thank you very much for reporting the issue! 
We have fixed it. Have fun using the software!
