### ISSUE TITLE
Under-sampling both ends of reference genome

### ISSUE THREAD

**Issue by evgisa** [lykaust15/DeepSimulator#16]
Hi! When simulating the reads of a linear sequence, it results in the under-sampling of both ends (mostly in the beginning) even with high coverages (>100X) . So, when reconstructing the reference sequence using canu (https://github.com/marbl/canu) both ends are missing, leading to an output shorter than expected. Do you know if this is the case when using the real nanopore sequencer and what to do to overcome this issue? Thank you and have a good day!

**Comment by lykaust15** [comment]
Hi, based on my previous experience of analyzing the real Nanopore data, we can face the same problem of low coverage at both ends of the linear reference genome. The easiest way of fixing the problem is simulating the reads of the circular genome.

**Comment by lykaust15** [comment]
But notice this is a quick fix of the problem in using the simulator. In fact, in reality, there are lots of species having the linear genome. Performing wet experiments will naturally result in low coverage in both the ends of the genome.

**Comment by evgisa** [comment]
Ok, thank you for the answer!
