### ISSUE TITLE
Changing N in main.sh affects signal generation

### ISSUE THREAD

**Issue by MolEcologist** [lykaust15/DeepSimulator#2]
Hi, I've modified main.sh so i produce 50 sequences as opposed to 10, however when I executed the script, i get the following error:

./main.sh -f /media/.../.../NanoSim-master/simulated_reads.fasta
Executing the preprocessing step...
Finished the preprocessing step!
Running the context-dependent pore model...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:14<00:00,  2.62it/s]
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    arg.output+'_{}.txt'.format(id_list[i]))
  File "main.py", line 99, in write_alpha_dis
    with open(file_name, 'w') as f:
IOError: [Errno 36] File name too long: '../../signal/signal_CACAACACAGCAAATACACACAGGAGGAGTA...GAAGG>CM000073.5_216002466_perfect_12451_R_0_26667_0TGTAATGTTTAGGGATTTTAAATGCATCCATCCCACTTTCAATTAAGATTTGCCGCCTGGTTGGAGCTGGTCGTTCCTTCTGTACTGGTGTCATGATCTTCCTCAGGCAGTGTTACCCCCCTTGGAACTATGTTGGAAGACTGA....TCGCGAGTGGAAACCCTCCCACCTTCCGTCTTTGGTCGTGGTAGAAACTCCGCGCCGTTCTCACAGCTCTCTACAAAGACTCACATTAAATACTTTTGGTAGCA.txt'
Finished generate the simulated signals!
Converting the signal into FAST5 files...

I've omitted some of the sequence for obvious reasons, however this can result in multiple sequences  and their names being incorporated into filename, resulting in sometimes only 1 of the reads (out of 50) being processed into a fast5. I'm not sure if this is because i upped the number of sequences being generated, but it happens even when I set n at 20, and unfortunately I need to generate hundreds of sequences

**Comment by lykaust15** [comment]
@MolEcologist 
May I have you sampled read file? It seems there are some format problems with it.
Usually, the signal file should have the following names:
```
signal_0.txt  signal_2.txt  signal_4.txt  signal_6.txt  signal_8.txt
signal_1.txt  signal_3.txt  signal_5.txt  signal_7.txt  signal_9.txt
```
I think because of the format problem, the program using the sequence as the file name directly, which cause that os level problem.

**Comment by MolEcologist** [comment]
Please find attached, it generates the correct signal files - for example it generates signal files up to signal_12.txt, and then no longer generates them correctly:

[sampled_read.fasta.txt](https://github.com/lykaust15/DeepSimulator/files/1914269/sampled_read.fasta.txt)

**Comment by lykaust15** [comment]
@MolEcologist 

Thank you! The bug has been found and fixed.
Have a try please.

**Comment by MolEcologist** [comment]
Thanks! It's working now, thanks for fixing the bugs so quickly!
