### ISSUE TITLE
guppy

### ISSUE THREAD

**Issue by lfaino** [lykaust15/DeepSimulator#20]
Dear Developper,
can I use data basecalled by guppy to generate synthetic reads?

Cheers
Luigi

**Comment by realbigws** [comment]
Hi, Luigi.

I think it shall be OK.

The underlying reason is that DeepSimulator only tries to simulate the raw
signal, and the final output reads could be generated by whatever
base-callers.

You may use Guppy to have a look, and hopefully you would get the desired
result.

Best,
-Sheng

**Comment by realbigws** [comment]
Dear  Luigi,

I have generated a new version of DeepSimulator, which tries to fix a
series of minor issues, and to put a large effort for the description of
the parameters in "deep_simulator.sh".

Please find this new branch below:
https://github.com/lykaust15/DeepSimulator/tree/experiment

please check the description by typing "./deep_simulator.sh".

I'm welcome to all the new suggestions raised by you.

Best,
-Sheng
