### ISSUE TITLE
new error model

### ISSUE THREAD

**Issue by yjx1217** [lykaust15/DeepSimulator#21]
Dear Developers,

I noticed that the simulated reads generated by DeepSimulator is substantially worse compared with the real nanopore reads (R9.4) generated in house, making the simulated data somewhat unrealistic. I assume this is because the original training data for DeepSimulator is based on the real reads produced by much older version of the technology (maybe R7?). Also, given that guppy has replaced albacore for nanopore basecalling and shows superior accuracy, it will be good the new model could account for this as well. So in sum,   it will be very helpful if the developers can update the error models along the development of the nanopore technology on both hardware and software sides.

Best,
Jia-Xing

**Comment by lykaust15** [comment]
> I noticed that the simulated reads generated by DeepSimulator is substantially worse compared with the real nanopore reads (R9.4) generated in house, making the simulated data somewhat unrealistic.

Could you specify what you mean by "substantially worse"? What criteria did you use? What parameters did you use to generate the results? It is dogmatical and irresponsible to attack and defame a tool without specifying the particular condition it performs badly, especially considering this tool has been peer-reviewed and you have the conflict of interest.

**Comment by yjx1217** [comment]
Hello,

By "substantially worse", I mean in terms of both mean/median length (4.5 kb vs. 8-10 kb) and quality  (8.3 vs. 9-10 )compared with real reads coming from R9.4 flowcell.  I ran deepsimulator with default parameters. 

Also, I have to point out that I don't see how my comments are "dogmatical and irresponsible attack" and how I could have "conflict of interest" ... I am simply pointing out the difference between simulated reads and the real reads produced by the latest nanopore technology for your future development given the rapid progressing pace of the nanopore technology itself ... 

Best,
Jia-Xing

**Comment by lykaust15** [comment]
OK, thank you for providing the details! We will update the simulator in according to LC this year.

Without details, the comments can be misleading, just like what you did again in the previous comments. You were taking out pieces of my sentences.

**Comment by realbigws** [comment]
On Thu, May 30, 2019 at 3:16 AM Jia-Xing Yue <notifications@github.com>
wrote:

> Hello,
>
> By "substantially worse", I mean in terms of both mean/median length (4.5
> kb vs. 8-10 kb) and quality (8.3 vs. 9-10 )compared with real reads coming
> from R9.4 flowcell. I ran deepsimulator with default parameters.
>

Hi, Jia-xing.

1) about the read quality:

By default, our simulator will produce the reads with 85-88% accuracy, by
the aid of Albacore basecaller.

According to our paper as well as the instructions, it is possible to
adjust the parameters for producing high-quality or low-quality reads.

For example, by tuning the "-s noise_std" and/or "-f filter_freq" parameter
shall fulfill this purpose.

If you would like DeepSimulator to produce high-quality reads (9-10) from
R9.4 flowcell, simply use "-s 1.0" shall be able to do that.


2) about the read length:

For the read-length issue, currently, we only provided three distribution
according to the statistics: (1) beta_distribution, (2) alpha_distribution,
(3) mixed_gamma_dis (by default).

In the next release, we will allow some tunable parameters to control the
length of the reads.


At last, we thank you again for pointing out the issues in DeepSimulator.

Best,
-Sheng

**Comment by yjx1217** [comment]
Hi Sheng,

Thank you very much for the detailed information! 

A suggestion that I could think of for the future version of DeepSimulator is to pre-define a set of error models with different quality/length combination corresponding to different major version of nanopore flowcell release so that the users can easily pick the one that suits the best of their needs.

On a different note, another problem that I have when running DeepSimulator is that it is very computationally intensive (i.e. cpu/ram/disk) even for simulating reads for small genomes. I understand it might be difficult for decreasing the cpu and ram usage but at least it should be possible to provide a parameter for the users to allow for automatically deleting un-needed intermediate files (e.g. the raw signal and alignment files when the .fast5 files have been generated). For my case, I was simulating 50x  nanopore reads for arabidopsis genome (~120-130 mb) and it costs ~500 GB disk space during the simulation, which is way too much I guess.  

Thanks and have a great weekend!

Best,
Jia-Xing

**Comment by realbigws** [comment]
On Sat, Jun 1, 2019 at 3:45 AM Jia-Xing Yue <notifications@github.com>
wrote:

> Hi Sheng,
>
> Thank you very much for the detailed information!
>
> A suggestion that I could think of for the future version of DeepSimulator
> is to pre-define a set of error models with different quality/length
> combination corresponding to different major version of nanopore flowcell
> release so that the users can easily pick the one that suits the best of
> their needs.
>

Excellent suggestion ~~

We shall definitely take your advice into our next release, and will
certainly acknowledge your suggestion in the acknowledgments.

On a different note, another problem that I have when running DeepSimulator
> is that it is very computationally intensive (i.e. cpu/ram/disk) even for
> simulating reads for small genomes. I understand it might be difficult for
> decreasing the cpu and ram usage but at least it should be possible to
> provide a parameter for the users to allow for automatically deleting
> un-needed intermediate files (e.g. the raw signal and alignment files when
> the .fast5 files have been generated). For my case, I was simulating 50x
> nanopore reads for arabidopsis genome (~120-130 mb) and it costs ~500 GB
> disk space during the simulation, which is way too much I guess.
>

Yep, this is another major issue in the current version of DeepSimulator.
However, as you know that even the compressed FAST5 files will have
extremely large volumes.

A possible solution is to generate ~5000 signals in a batch, and compress
them in the multi-FAST5 file. However, this will only reduce about 60% disk
space, which is still too large to accept.

Anyway, thank you for pointing this out. We shall certainly try to solve
this issue.

Best,
-Sheng

**Comment by realbigws** [comment]
On Sat, Jun 1, 2019 at 3:45 AM Jia-Xing Yue <notifications@github.com>
wrote:

> Hi Sheng,
>
> Thank you very much for the detailed information!
>
> A suggestion that I could think of for the future version of DeepSimulator
> is to pre-define a set of error models with different quality/length
> combination corresponding to different major version of nanopore flowcell
> release so that the users can easily pick the one that suits the best of
> their needs.
>
> On a different note, another problem that I have when running
> DeepSimulator is that it is very computationally intensive (i.e.
> cpu/ram/disk) even for simulating reads for small genomes. I understand it
> might be difficult for decreasing the cpu and ram usage but at least it
> should be possible to provide a parameter for the users to allow for
> automatically deleting un-needed intermediate files (e.g. the raw signal
> and alignment files when the .fast5 files have been generated). For my
> case, I was simulating 50x nanopore reads for arabidopsis genome (~120-130
> mb) and it costs ~500 GB disk space during the simulation, which is way too
> much I guess.
>

Hi, Jia-Xing.

I have generated a new version of DeepSimulator to solve the issues you've
pointed out, especially on the extremely large disk space.

Please find this new branch below:
https://github.com/lykaust15/DeepSimulator/tree/experiment

In this version, we also tried our best to write a description of the
parameters in "deep_simulator.sh", please check them by typing "
./deep_simulator.sh".

I'm welcome to all the new suggestions raised by you.

Best,
-Sheng

**Comment by yjx1217** [comment]
Hi Sheng,

Many thanks for the efforts! I will give it a try next week and let you know how it goes.

Best,
Jia-Xing

**Comment by yjx1217** [comment]
Hi Sheng @realbigws ,

Thanks again for the improvements!  The new version indeed works better in terms of speed and  disk usage. I got the following error in the test that I carried out last week:
`...
Finished generate the simulated signals and fast5 files!
Running Basecalling...
   Basecalling with Guppy_GPU...
/home/jxyue/DeepSimulator_exp/base_caller/guppy_3.1.5/ont-guppy/bin/guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
Basecalling finished!
Checking the read accuracy...
awk: cmd. line:1: fatal: division by zero attempted
Here is the mapping identity:  of 0 (pass 0 + fail 0) reads passed base-calling.`

I guess this is because the default basecaller guppy-gpu requires libcuda, which has not been installed on our cluster. I guess this might happen for many other users so it might be better to set guppy-cpu as the default basecaller instead for better robustness. I have started a new run with guppy-cpu (enabled by setting -B 2 for deepsimulator) and I will let you now how it works.

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing:

Thank you very much for trying the new version of DeepSimulator!
Yes, from the error message, it seems the problem is related to libcuda.
That's a nice suggestion to use guppy-cpu as the default setting. We will have a discussion of that. One concern of using guppy-cpu as the default setting is that guppy-cpu can be very slow, compared with the gpu version and Albacore.
We will let you know when we come up with a solution to the problem you rise.
Thank you very much again for trying DeepSimulator1.5. Let's keep in touch.

Sincerely,
Yu

**Comment by yjx1217** [comment]
My new run has finished and the simulated reads indeed look much more realistic in terms of both quality and length compared with the latest ONT real reads.

Many thanks for the new version upgrade!

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, thank you very much for your positive feedback!

Sincerely,
Yu
