### ISSUE TITLE
libcuda.so.1 problem when run deep_simulator.sh

### ISSUE THREAD

**Issue by Lemon-Liu** [lykaust15/DeepSimulator#28]
Dear developers,

After installing DeepSimulator, I tried `./case_study.sh -f example/artificial_human_chr22.fasta`, everything is fine. 

However, when I tried `./deep_simulator.sh -i example/artificial_human_chr22.fasta` in the 'DeepSimulator' dir, there is a problem of 'guppy_basecaller':

`/mypath/DeepSimulator/base_caller/guppy_3.1.5/ont-guppy/bin/guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
Basecalling finished!`

Here is the whole output in the screen:

```shell
Pre-process input genome...
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Pre-process input genome done!
Executing the preprocessing step...
('The average length is: ', 7981.6000000000004)
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Finished the preprocessing step!
Key parameters for simulation are shown below
    event_std    : 1.0
    filter_freq  : 950
    signal_std   : 1.0
Running the context-independent pore model...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:03<00:00, 29.05it/s]
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Finished generate the simulated signals and fast5 files!
Running Basecalling...
   Basecalling with Guppy_GPU...
/mypath/DeepSimulator/base_caller/guppy_3.1.5/ont-guppy/bin/guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
Basecalling finished!
Checking the read accuracy...
awk: cmd. line:1: fatal: division by zero attempted
Here is the mapping identity:  of 0 (pass 0 + fail 0) reads passed base-calling.
```

and the  'pass.fastq' file is null.

Do you have any suggestion to fix it?
Thanks ahead.

Mia

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest!
The problem is related to the fact that Guppy_GPU requires the installation of CUDA library. If you want to take advantage of GPU for the computation acceleration, you can consider installing that. 
Otherwise, you can consider using '-B 2' to use Guppy_CPU or '-B 3' to use Albacore.

Sincerely,
Yu
