### ISSUE TITLE
A potential bug related with read coverage for v1.5?

### ISSUE THREAD

**Issue by yjx1217** [lykaust15/DeepSimulator#29]
Hello,

I have just noticed that the resulting coverage of reads simulated by DeepSimulator v1.5  (github commit: d04ba3a) is not what I specified when running DeepSimulator. For example, with the following command, I specified a desired coverage of 50X but got 91X simulated reads in the end. It was fine in v1.0 version in contrast, so could you please check if there is a hidden bug resulting this issue in v1.5. Thanks in advance!

$deepsimulator_dir/deep_simulator.sh -H $deepsimulator_dir -c 16 -i ref_genome.fa -B 2 -K 50 -S 20190518 -o output_prefix_deepsimulator_out
 
Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing, thank you very much for reporting the bug! We have fixed it. Please have a try again.

**Comment by yjx1217** [comment]
Thanks for the quick fix!

Best,
Jia-Xing
