### ISSUE TITLE
DeepSimulator (branch discontinuous-fasta) dosen't handle multi-line fasta files correctly

### ISSUE THREAD

**Issue by yjx1217** [lykaust15/DeepSimulator#31]
Dear Developers,

I've just noticed a new issue with the newly added support for multi-fasta input genome:

When the multi-fasta input genome is in single line fasta format (i.e. without line wraps for the sequence lines), it works as expected. However, When the input genome is in multi-line fasta format (the long sequence line are folded into multi lines with line wrap at the end), DeepSimulator will just take the first line and ignore the remaining sequences of the same chromosome/contig/scaffold.

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Hi, Jia-Xing, thank you for reporting the issue. This issue will be fixed very soon.

**Comment by lykaust15** [comment]
Hi, I have hopefully fixed the bug. But I am currently on a vacation and I do not have access to a machine that can run the code. Please feel free to test it before I go back to my school on 17th this month.

**Comment by yjx1217** [comment]
Hi Yu,

Thanks for the fix! I am also on vacation right now but  will have it
tested soon after I get back before the weekend.

Best,
Jia-Xing

**Comment by lykaust15** [comment]
Dear Jia-Xing:

The bug should be fixed now. Please have a try when you are free. Remember to install Biopython within the environment.

Sincerely,
Yu

**Comment by yjx1217** [comment]
Thanks Yu! I think it works as expected now. 

Best,
Jia-Xing
