### ISSUE TITLE
Amplicon reads simulation

### ISSUE THREAD

**Issue by MaestSi** [lykaust15/DeepSimulator#32]
Dear DeepSimulator developers,
I would like to use your tool for simulating nanopore reads, resulting from amplicon sequencing. However, all the reads in pass.fastq have exactly the same errors. Are there any parameters that I am missing? I tried both the context dependent and context independent pore models, but the results were very similar.
Moreover, when I set` -n -1`, it looks like the `-K` parameter value has no effect, since one single read is produced instead of K reads.
Thanks in advance,
Simone

**Comment by MaestSi** [comment]
I realised that performing a for loop and setting a different `-S` value at each iteration does the job.
For example:
`for f in {1..10}; do ./deep_simulator.sh -i template_reference.fasta  -B 2 -n -1 -S $f -o "template_reference_DeepSimu_"$f; done`
generates 10 amplicon-like reads.
Let me know if there are better solutions, or if this one should be ok.
Thanks,
Simone

**Comment by lykaust15** [comment]
Hi Simone:

Yes, I think that's a reasonable solution to your problem. `-S` is used to control random seed, which can introduce different errors to different sequences.

Sincerely,
Yu

**Comment by MaestSi** [comment]
Thank you very much,
Simone
