### ISSUE TITLE
Install on MacOs

### ISSUE THREAD

**Issue by arsthilaire** [lykaust15/DeepSimulator#37]
Hi,

I wanted to use DeepSimulator, but I only have a computer running MacOs. When I try to install DeepSimulator, I have problems with albacore and guppy because they are meant for linux users. Do you have the wget link for macOs ?

Thank you!

**Comment by lykaust15** [comment]
Here are the link addresses:
https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy-cpu_3.5.2_osx64.zip
https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.3.4-cp36-cp36m-macosx_10_11_x86_64.whl

However, we still suggest you use the Linux version. We have not tested on macOS and we do not have a plan to do so. You can have a try with your own risk. Good luck!
