### ISSUE TITLE
More detailed instructions (I'm not so sure how to get started)

### ISSUE THREAD

**Issue by sickerin** [lykaust15/DeepSimulator#4]
Hello,

I'm interested in using the DeepSimulator to generate simulated reads for S. cerevisiae (**including spliced reads**), strain(BY4741), genome annotation (SacCer3). I would be grateful if you could write more detailed instructions or give more examples (perhaps something like bcgsc/Nanosim did). I presume to generate simulated reads, I would have to train a customized model for my genome, and I'm not so sure to as to what "the corresponding nanopore raw signals" are and how would I obtain them.

Thank you!
Daniel

**Comment by lykaust15** [comment]
Thank you very much for your interest in our work!
The corresponding raw signals is the experimental signal for a certain read, which can be considered as ground truth. We use cwdtw to align the read and the signal to obtain that.
If your primary goal is to get the read, the built in model is enough since our method is nanopore kit based instead of genome based. As long as the nanopore kit and the method does not change, our method will work. The genome type would not influence our method’s performance under most circumstances.

**Comment by sickerin** [comment]
Thank you for quick your reply,

So, for instance, if what I'm trying to do is to simulate this gene [(YBL027W)](https://www.yeastgenome.org/locus/S000000123#sequence), to find out what are the possible reads nanopore will simulated as, I don't really have to create a model. 
Instead, do I just put that gene sequence into a fasta file then run `./main.sh -f ./mygene.fasta`. This will then output a file with a possible simulation of that gene by nanopore, is that correct? Moreover, is it possible to specify the number of simulated reads, or how might I do that?

Daniel

**Comment by lykaust15** [comment]
Yes, exactly.

For the number of reads, you can specify it by changing one line of the ```main.sh``` file.
In the ```main.sh``` file, there is:
```
python2 ./sampling_from_genome/sampling.py \
	-i $FULLFILE \
	-p ./$FILENAME/sampled_read \
	-n 10 \
	-d 2 \
	-c 0
```
```-n 10``` meaning the number of simualted reads is 10. You can specify any number you want. You can try from small number to first make sure it works before try large number. It can take longer time than NanoSim for simulating the same number of reads. You can refer the supplementary material of the paper to have a basic understanding of the computational resource requirement.

In the supplementary material, we also provided detailed parameters description with which you can control DeepSimulator.

[Supplementary material of DeepSimulator](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/34/17/10.1093_bioinformatics_bty223/2/bty223_supplemental_materials.pdf?Expires=2147483647&Signature=v5FSUbbU4eVfQdIo3H3Xrsq6CFVh8azonSxGg1WaAL35maQ0zqIPzdRPTTGUUhlzkLYBnU3Fi4G1DRcXc5YDD4Ea~8ic56zpjBNWQ4qqSZabjH9XwTFyPTbh6IKaHkULi9zKfSl02MxxXfqEJ0Xi72AKRv0Up4j~baWrfyUEKYtEVkzJbpbyAsnZhvPh2WSbFXyPhRhBn~fH9XfrEO9hbMQPSrT9di2Ho85ZBbZ2xS0P~J8sZyi91ulXQHfYSH5rbdaTNAAxRCVbLQUi3iKbJFE5Bl0de66w0mdjfgIZGqrBY9uPoXwW4MYf6H7OwmVXnDc-sjoe73UxO4xHRF17Ag__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA)

**Comment by sickerin** [comment]
Thank you, I'll let you know how it goes :)
