### ISSUE TITLE
Raw signal per called base

### ISSUE THREAD

**Issue by MMAThijssen** [lykaust15/DeepSimulator#5]
Hello!

I am using DeepSimulator to generate raw signals. I was wondering if there is a way to know which raw signals underlie a basecall. When I was checking the code, I saw that the signal was written six times to the text file. This number does not match number of signals in Raw/Reads/Read_{}/Signal.

Can you please clarify how many signals underlie a basecall or how this is determined?

Thank you in advance!

**Comment by lykaust15** [comment]
Hi! Thank you very much for your question.
The repeat time is simulating the real procedure of Nanopore sequencing. In the real experiment, each base is also detected multiple times. The downstream basecaller has already taken that into consideration.

**Comment by MMAThijssen** [comment]
Thank you for your quick response! 

Does this mean that each base is detected six times (so represented six times in the raw signal)? Or does this number vary? 
In reality, the number of measurements per base varies, but since this is a simulation I am not sure how this is implemented. My goal is to connect the raw signals to the bases.

**Comment by lykaust15** [comment]
Yes, it varies.
Connecting raw signals with the bases can be a little bit difficult. You can consider using the tool that we use cwdtw: https://github.com/realbigws/cwDTW

**Comment by MMAThijssen** [comment]
Okay, that is unfortunate for me. Thank you for your help!
