### ISSUE TITLE
Repeats

### ISSUE THREAD

**Issue by mattdmem** [lykaust15/DeepSimulator#6]
Hello,
I'm testing this tool with a fasta file that contains a repetitive DNA structure (with plenty of flanking sequence). The tool performs pretty badly at simulating reads from this structure. I have 1000 repeats of GGCCCC, however even with settings to produce "perfect" results the structure looks like this in the fastq:

`TACGTTTCGTTCGTTCGTTACGTTTGTTCGTTCGTTCGTTTACGTTTACGTTCGTTTACGTTTACGTTTACGTTCGTTTGTTCG....`

Real world nanopore data shows that we can sequence this accurately. Do I need to train a new model? Or are there other settings I can change?

Thanks

Matt

**Comment by lykaust15** [comment]
Hi, mattdmem, thank you very much for your interest in our tool!
For the built-in model, we did not consider such case with lots of repeats. Probably you need to train a customized model. To train the model, you need to first build up a training data probably using a dynamic time warping tool as we used: https://github.com/realbigws/cwDTW. You can refer the link for more details.

**Comment by MaestSi** [comment]
Hi @mattdmem ,
I am trying to simulate data with long repeats too, and apparently DeepSimulator is struggling to simulate those data too, as the 3bp motif is changed from CAG to CAA in most repeats. I was wondering if you succeeded in training a customized model as suggested or not.
Thanks,
Simone
