### ISSUE TITLE
output directory

### ISSUE THREAD

**Issue by jelfiedia** [lykaust15/DeepSimulator#7]
Hi, thanks for this great piece of software!.
One note; the output dir as set by -o in deepsimulator.sh, is never used, instead the default is always set. 
The reason for this could be that you set the given value to the variable output_root, but after this use out_root.

**Comment by lykaust15** [comment]
Hi, thank you very much for reporting the bug!! We really appreciate it!!
Now the bug should be fixed. Please have a try. Feel free to let us know if you have more questions.
Have a good day!
