### ISSUE TITLE
RNA-seq simulation

### ISSUE THREAD

**Issue by daniellezhang** [lykaust15/DeepSimulator#9]
I am wondering whether DeepSimulator can simulate RNA-seq. If so, what should the input be and what is the optimal parameters?

Thanks

**Comment by lykaust15** [comment]
Hi, thank you very much for your interest!

Currently, DeepSimulator is unable to perform that. But we are considering equipping it with that function. Hopefully, we will release DeepSimulator2.0, which the function of simulating RNA seq and DNA methylation.

**Comment by nemitheasura** [comment]
Hi, it's been more than a year since this thread was closed. Are you still working on RNA-seq simulation mode?
